// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJtd4we3uInWg6l3hZnkc0vFBzCeUJ3nw',
    appId: '1:834054083200:web:7e28a2c561b73225e28c65',
    messagingSenderId: '834054083200',
    projectId: 'authmhs',
    authDomain: 'authmhs.firebaseapp.com',
    storageBucket: 'authmhs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuxd_zPlrTuTGVT-TPFGAnhUC7RLy_2yo',
    appId: '1:834054083200:android:9c9bb84803c5766de28c65',
    messagingSenderId: '834054083200',
    projectId: 'authmhs',
    storageBucket: 'authmhs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIYk9lGryxG3jM3k1zH88EqUV93gmu4LE',
    appId: '1:834054083200:ios:29f826851d1f2e8ce28c65',
    messagingSenderId: '834054083200',
    projectId: 'authmhs',
    storageBucket: 'authmhs.appspot.com',
    iosClientId: '834054083200-lq73mgbc1tg88iot1s9o0lk7fks1sttu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mhsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIYk9lGryxG3jM3k1zH88EqUV93gmu4LE',
    appId: '1:834054083200:ios:29f826851d1f2e8ce28c65',
    messagingSenderId: '834054083200',
    projectId: 'authmhs',
    storageBucket: 'authmhs.appspot.com',
    iosClientId: '834054083200-lq73mgbc1tg88iot1s9o0lk7fks1sttu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mhsApp',
  );
}
